baseURL: https://elegant-carson-e21034.netlify.app
languageCode: fr
title: Normes de TC
theme: "PaperMod"

defaultContentLanguage: 'fr'
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    fr:
        languageName: "French"
        weight: 1
        menu:
            main:
                - name: Recherche
                  url: search/
                  weight: 10
                # - name: Tags
                #   url: tags/
                #   weight: 10

    # fr:
    #     languageName: ":fr:"
    #     languageAltTitle: French
    #     weight: 2
    #     title: PaperModL2
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
    #         # imageUrl: "#"
    #         # imageTitle: my image
    #         # imageWidth: 120
    #         # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Tags
    #               url: tags
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: Tags
    #               url: tags
    #               weight: 10
    #             - name: Categories
    #               url: categories
    #               weight: 10
    #             - name: Series
    #               url: series
    #               weight: 10
    #             - name: NullLink
    #               url: "#"
    #             - name: NullLink2
    #               url: "#"
    #             - name: NullLink3
    #               url: "#"

    # fa:
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     menu:
    #         main:
    #             - name: Tags
    #               url: tags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Francis Chabouis
    # author: ["Me", "You"] # multiple authors


    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    applause: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Normes de TC"
        Content: |
            ## Contexte 
            Le Règlement Délégué (UE) 2017/1926 De La Commission du 31 mai 2017 (complétant la directive 2010/40/UE du Parlement européen et du Conseil en ce qui concerne la mise à disposition, dans l'ensemble de l'Union, de services d'informations sur les déplacements multimodaux), et en droit français, la LOI n° 2019-1428 du 24 décembre 2019 d'orientation des mobilités, notamment dans son article 25, dispose que les données statiques et dynamiques appelées à être ouvertes, et applicables aux normes NeTex et SIRI, soient représentées par des profils nationaux minimaux, qui sont une déclinaison de ces normes aux besoins métiers en France.
            Conformément à l'arrêté du XXX, les spécifications référencées ci-dessous correspondent aux versions officielles et en vigueur des profils des normes à employer en France. Il est donc nécessaire de fournir les données selon ces spécifications techniques pour être conforme au cadre juridique.


            ## Descriptif
            Les liens ci-dessous permettent d'accéder au format web au contenu des profils. Sur chacune des pages, il est possible de télécharger une version pdf du document correspondant. Un espace [Github](https://github.com/fchabouis/normes-tc-content-test), hébergeant le contenu de ces documents, offre par ailleurs la possibilité d'explorer et d'exploiter leur contenu au format markdown.

            ## Gouvernance
            Les spécifications techniques sont élaborées et maintenues par le groupe de travail GT7 relatif à l'information voyageur (AFNOR BNTRA/CN03/GT7). Des commentaires peuvent toutefois être formulés sur les pages web de chaque profil, ainsi que directement sur l'[espace de commentaires Github](https://github.com/fchabouis/normes-tc-content-test/issues), permettant à la communauté de producteurs et de réutilisateurs de données de remonter des informations au groupe de travail.
    socialIcons:
        - name: github
          url: "https://github.com/fchabouis"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/fchabouis/francis-chabouis-blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    label:
        text: 'Normes de transport en commun'
        icon: '/ministere_transition_ecologique_logo.png'
        iconHeight: 80

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true